#sudo: required
dist: trusty # Ubuntu 14.04 LTS
language: python
matrix:
 include:
  - python: "2.7"
  - python: "3.3"
  - python: "3.5"
  - python: "3.6"
  - python: "nightly"
 allow_failures:
  - python: "2.7"
install: true
script:
  - python polygon.py 4 0 4 2 8 5 5 1 6

notifications:
 email:
  recipients:
   - patryk.ligenza@smcebi.edu.pl
  on_success: never
  on_failure: change