#sudo: required
dist: trusty # Ubuntu 14.04 LTS
language: python
matrix:
 include:
  - python: "2.7"
  - python: "3.3"
  - python: "3.5"
  - python: "3.6"
  - python: "nightly"
 allow_failures:
  - python: "2.7"
install: true
script:
  - python polygon.py 4 0 4 2 8 5 5 1 6
  - python polygon.py 1 2 4 6 7 1 2 54 67 100
  - python polygon.py 5 5 5 5 5 5 5 5 5 5
  - python polygon.py
  - python polygon.py 1 5 4 6
  - python polygon.py 1 6 0.4 -2.4
  - python polygon.py 3 4 5 11 12 8 9 5 5 6
  - python polygon.py -2 14 -3.4 7.1 6.0 -10 7 15 132.5 34.4
  - python polygon.py -2 14 -3.4 7.1 6.0 -10 7 15 132.5
  - python polygon.py -2 14 -3.4 7.1 6.0 -10
  - python polygon.py -2 14 -3.4 132.5 34.4 7.1 6.0 -10 7 15
  - python polygon.py 2 4 3 7 6 10 7 15 14 34
  - python polygon.py 2 4 3 7 14 34 6 10 7 15
  - python polygon.py 2 4 14 34 6 10 7 15 3 7

notifications:
 email:
  recipients:
   - patryk.ligenza@smcebi.edu.pl
  on_success: never
  on_failure: change